### ISSUE TITLE
dashboard view error

### ISSUE THREAD

**Issue by Balbenar** [nurikk/z2m-frontend#1850]
### What happened?

When filtering elements in dashboard view by typing name, there is error "m.toLowerCase is not a function"

Since upgrade to 1.34.0

[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/13561519/initialState.json.zip)

### What browsers are you seeing the problem on?

Firefox

### Relevant stacktrace

```shell
**Current url**: http://192.168.191.22:8080/#/dashboard
**Previous url**: 


**Error type**: TypeError
**Error message**: m.toLowerCase is not a function



h1t/u</<@http://192.168.191.22:8080/assets/index-89f5fdf3.js:99:5680
h1t/u<@http://192.168.191.22:8080/assets/index-89f5fdf3.js:99:5671
a1t/<@http://192.168.191.22:8080/assets/index-89f5fdf3.js:99:3159
Ykt@http://192.168.191.22:8080/assets/index-89f5fdf3.js:99:2960
a1t@http://192.168.191.22:8080/assets/index-89f5fdf3.js:99:3130
h1t@http://192.168.191.22:8080/assets/index-89f5fdf3.js:99:5592
y2@http://192.168.191.22:8080/assets/index-89f5fdf3.js:41:19551
rC@http://192.168.191.22:8080/assets/index-89f5fdf3.js:43:3143
l9@http://192.168.191.22:8080/assets/index-89f5fdf3.js:43:44877
i9@http://192.168.191.22:8080/assets/index-89f5fdf3.js:43:39821
d3e@http://192.168.191.22:8080/assets/index-89f5fdf3.js:43:39747
Yy@http://192.168.191.22:8080/assets/index-89f5fdf3.js:43:39596
hC@http://192.168.191.22:8080/assets/index-89f5fdf3.js:43:35959
r9@http://192.168.191.22:8080/assets/index-89f5fdf3.js:43:34906
S@http://192.168.191.22:8080/assets/index-89f5fdf3.js:28:1549
L@http://192.168.191.22:8080/assets/index-89f5fdf3.js:28:1907
@http://192.168.191.22:8080/assets/index-89f5fdf3.js:18:12140
RI@http://192.168.191.22:8080/assets/index-89f5fdf3.js:18:11880
DP@http://192.168.191.22:8080/assets/index-89f5fdf3.js:18:11944
```

### Did you download state.json.zip?

I will attach state.json.zip
